version: "3.7"
services:
  rstudio:
    container_name: rstudio
    build: .
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=pass
      - USERID=1000
    volumes:
      - ".:/home/rstudio"
